version: 2.1
default: &default
  docker:
    - image: cimg/node:16.10

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *default
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *default
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

